import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {Font} from '~assets/fonts';

export const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerDateFilter3: {
    flexDirection: 'row', 
    alignItems: 'center', 
    marginLeft: 30
  },
  containerDropDown: {
    zIndex: 1,
    alignItems: 'center', 
    justifyContent: 'center'
  },
  containerModal: {
    justifyContent: 'center',
    alignItems: 'center',
    height: hp('100%'),
    width: wp('100%'),
  },
  containerInfo: {
    height: hp('73.5%'),
    width: wp('50%'),
    borderRadius: wp('0.8%'),
    backgroundColor: 'white',
  },
  containerBody: {
    margin: 15,
  },
  containerBody2: {
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'row',
    backgroundColor: '#007173',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 35,
  },
  containerBody3: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 35,
    marginTop: 10,
  },
  containerBtnEvaluate: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 315,
  },
  containerRow: {
    marginTop: 5,
    flexDirection: 'row',
    width: wp('50%'),
    alignItems: 'center',
    justifyContent: 'center'
  },
  line: {
    marginVertical: 5,
    height: 1,
    backgroundColor: '#E0E0E0'
  },
  textModal1: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#FEFEFE',
    marginLeft: 16,
    width: 275
  },
  textModal2: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#FEFEFE',
    width: 200
  },
  textModal3: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#FEFEFE',
    width: 200
  },
  textModal4: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#FEFEFE',
    width: 200,
    marginLeft: 10,
  },
  textBtn: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#FEFEFE',
  },
  text2: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#007173',
    marginRight: 10,
    marginTop: 15,
  },
  text: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    marginRight: 10,
  },
  text3: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '200',
    fontSize: 15,
    color: 'black',
    marginRight: 10,
  },
  textCriteria: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#454545',
    width: 257,
    marginLeft: 16,
  },
  textData: {
    textAlign: 'center',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    color: '#454545',
    width: 100,
  },
  btnEvaluate: {
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    backgroundColor: '#007173',
    borderRadius: 5, 
    height: 35,
    width: 100,
  },
  textValidNumber: {
    padding: 5,
    textAlign: 'center',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#C2C2C2',
    height: 35,
    width: 125,
  },
  textInput: {
    width: 175,
    height: 35,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginVertical: 10,
  },
  table: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 16,
    margin: 24,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
    paddingBottom: 10,
    width: wp('50%'),
    height: hp('70%'),
  },
  row: {
    flexDirection: 'row',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#007173',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#007173',
    marginTop: 16,
    padding: 16,
  },
  rowData: {
    flex: 1,
    flexDirection: 'row',
  },
  headerColumn1: {
    width: 200,
    flex: 1,
    fontFamily: Font.LexendDeca_Regular,
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: 16,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  cell: {
    flex: 1,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: 'black',
    borderWidth: 0.5,
    borderColor: '#F0F0F0',
    padding: 16,
  },
  cell2: {
    flex: 1,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: 'black',
    borderWidth: 0.5,
    borderColor: '#F0F0F0',
    padding: 16,
  },
  titleParams: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 28,
    textAlign: 'center',
    color: '#007173', 
  },
  containerPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    alignSelf: 'flex-end',
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationItem: {
    color: 'black',
    padding: 10,
    marginHorizontal: 5,
    borderRadius: 5,
  },
  paginationItemSelected: {
    flexDirection: 'row',
    backgroundColor: '#007173',
  },
  txtPage: {
    color: '#007173',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '200',
    textAlign: 'center',
    fontSize: 20,
  },
  txtPageFocused: {
    color: '#FFFFFF',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 20,
  },
  btnNext: {
    color: '#007173',
    marginHorizontal: 10,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 25,
  },
  btnPrevious: {
    color: '#007173',
    marginHorizontal: 10,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 25,
  },
  containerBtnEdition: {
    flexDirection: 'row', 
    justifyContent:'center',
  },
  btnEdition: {
    backgroundColor: '#FEFEFE', 
    borderWidth: 1, 
    borderColor: '#007173',
    borderRadius: 8,
    width: 135, 
    height: 35, 
    justifyContent:'center', 
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 10,
  },
  btnEditionSave: {
    justifyContent:'center', 
    alignItems: 'center',
    backgroundColor: '#007173', 
    borderWidth: 1, 
    borderColor: '#007173',
    borderRadius: 8,
    marginTop: 10,
    marginLeft: 10,
    width: 135, 
    height: 35,
    marginHorizontal: 250,
  },
  btnModalCancel: {
    justifyContent:'center', 
    alignItems: 'center',
    backgroundColor: '#FFFFFF', 
    borderWidth: 1, 
    borderColor: '#007173',
    borderRadius: 8,
    width: 135, 
    height: 40, 
    marginHorizontal: 10,
  },
  btnSave: {
    justifyContent:'center', 
    alignItems: 'center',
    backgroundColor: '#007173', 
    borderWidth: 1, 
    borderColor: '#007173',
    borderRadius: 8,
    width: 135, 
    height: 40, 
  },
  txtModalSave: {
    color: '#007173',
    fontWeight: '900'
  },
  txtBtnSave: {
    color: '#FFFFFF',
    fontWeight: '900'
  },
  txtBtnCancel: {
    color: '#007173',
    fontWeight: '900'
  },
})