import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {Font} from '~assets/fonts';

export const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerFilter: {
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent:'center', 
    marginTop: 50, 
    marginBottom: 35
  },
  containerDateFilter: {
    flexDirection: 'row', 
    alignItems: 'center', 
    marginRight: 30
  },
  containerBtnDate : {
    padding: 15, 
    justifyContent:'center', 
    borderWidth: 2, 
    borderRadius: 5, 
    borderColor: '#E0E0E0', 
    width: 300, 
    height: 50
  },
  table: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 16,
    margin: 24,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
    paddingBottom: 10,
    width: wp('50%'),
    height: hp('70%'),
  },
  row: {
    flexDirection: 'row',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#007173',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#007173',
    marginTop: 16,
    padding: 16,
  },
  rowData: {
    flex: 1,
    flexDirection: 'row',
  },
  header: {
    flex: 1,
    fontFamily: Font.LexendDeca_Regular,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  cell: {
    flex: 1,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: 'black',
    borderWidth: 0.5,
    borderColor: '#F0F0F0',
    padding: 16,
  },
  txtDate: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 23,
    color: '#007173',
    marginRight: 10,
  },
  titleParams: {
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 28,
    textAlign: 'center',
    color: '#007173', 
  },
  containerPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    alignSelf: 'flex-end',
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationItem: {
    color: 'black',
    padding: 10,
    marginHorizontal: 5,
    borderRadius: 5,
  },
  paginationItemSelected: {
    flexDirection: 'row',
    backgroundColor: '#007173',
  },
  txtPage: {
    color: '#007173',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '200',
    textAlign: 'center',
    fontSize: 20,
  },
  txtPageFocused: {
    color: '#FFFFFF',
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 20,
  },
  btnNext: {
    color: '#007173',
    marginHorizontal: 10,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 25,
  },
  btnPrevious: {
    color: '#007173',
    marginHorizontal: 10,
    fontFamily: Font.LexendDeca_Thin,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 25,
  }
})